name: fsbackup_server
version: 1.0.0
description: fsbackup engine
publish_to: none
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  worker_isolated:
    path: ../worker_isolated
  fsbackup_shared:
    path: ../fsbackup_shared
  os:
    path: ../os_utils

  ffi: ^1.1.2 #0.1.3
  meta: ^1.7.0
  win32: any
  shelf: 
  shelf_router:
  
dev_dependencies:
  pedantic: any
  test: any