name: fsbackup
description: fsbackup.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter    
  flutter_localizations:   #Add this line to multi-language-support
    sdk: flutter   #Add this line to multi-language-support
  intl: any  #Add this line to multi-language-support

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #xterm: ^2.5.0-pre
  #dartssh:
    #git:
      #url: https://github.com/TerminalStudio/dartssh
      #https://github.com/insinfo/dartssh

  #dartssh:
    #path: 
      #../dartssh
  path_provider: ^2.0.2 
  mailer: ^5.0.2 #Null safety
  dio: any
  http: any
  url_launcher: ^6.0.9
  objectdb: ^1.2.1+1 #database NoSQL não tem collections
  mongo_dart: ^0.7.1
  process_run: ^0.12.1+1    
  google_fonts: any
  flutter_svg: ^0.22.0
  fl_chart: ^0.36.4  
  provider: ^6.0.0
  data_table_2: ^2.1.1
  get_it: ^7.2.0
  page_transition: ^2.0.2
  uuid: any
  win32: any
  ffi: any
  cron: any
  cron_form_field: ^0.2.0
  queue: ^3.1.0
  #csv: any
  #os: ^0.1.2
  web_socket_channel: any
  teledart: ^0.2.1
  f_logs: ^2.0.0
  worker_isolated:
    path: packages/worker_isolated
  fsbackup_shared:
    path: packages/fsbackup_shared
  os:
    path: packages/os_utils
  slugify: ^2.0.0
  file_picker: ^4.0.3
  loading: ^1.0.2
  #mask_text_input_formatter: ^2.0.0
  #docking: ^0.6.0 #https://pub.dev/packages/docking

  #filesystem_picker:
    #path: packages/filesystem_picker

  libssh_binding: 
    path: packages/libssh_binding
  sftp_file_picker:
    path: packages/sftp_file_picker
  #dcli: any
  archive: ^3.1.5
  
dev_dependencies:
  #flutter_test:
    #sdk: flutter
  build_runner: any  
    
# The following section is specific to Flutter.
flutter:
  generate: true    #Add this line to multi-language-support
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/mongodb/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
