name: libssh_binding
description: libssh_binding
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.13.1 <3.0.0"

dependencies:
  ffi: any

dev_dependencies: 
  build_runner: any
  ffigen: any #^4.0.0
  


ffigen:
  name: 'test'
  description: 'Bindings to test'
  output: 'test.dart'
  llvm-path:     
    - 'C:\Program Files\llvm'      
  headers:
    entry-points:
      #- 'libssh/include/libssh/sftp.h'     
      - 'extra/test.h' 
    #include-directives:
      #- '**sftp.h'
      #- 'libssh/include/libssh/**'
      #- 'libssh/src/**'
  #compiler-opts:
    #- '-Ilibssh/'