name: libssh_binding
description: libssh_binding
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.14.1 <3.0.0"

dependencies:
  ffi: any

dev_dependencies: 
  build_runner: any
  ffigen: ^4.0.0
  
ffigen:
  name: 'Libssh'
  description: 'Bindings to libssh'
  output: 'libssh.dart'
  llvm-path:     
    - 'C:\Program Files\llvm'      
  headers:
    entry-points:
      - 'libssh/include/libssh/libssh.h'      
    include-directives:
      - '**libssh.h'
      #- 'libssh/include/libssh/**'
      #- 'libssh/src/**'
  

