name: sftp_file_picker_example
description: Demonstrates how to use 'sftp_file_picker'.
publish_to: none
version: 1.0.3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
  permission_handler: ^6.1.0
  sftp_file_picker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
