name: os
version: 1.0.0
description:
  Access to operating system APIs (using 'dart:ffi'). Virtual memory management, IPC pipes, file
  permissions, etc.
homepage: https://github.com/dart-interop/os

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  ffi: ^1.1.2 #0.1.3
  meta: ^1.7.0
  win32: any

dev_dependencies:
  pedantic: any
  test: any