name: sftp_file_picker
description: file or folder picker dialog. Allows the user to browse the file system and pick a folder or file.
version: 2.0.0
homepage: https://github.com/insinfo
#repository: https://github.com/insinfo
#issue_tracker: https://github.com/insinfo/issues
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  libssh_binding:
    path: ../libssh_binding

dev_dependencies:
  flutter_test:
    sdk: flutter
    

flutter:
